/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stock-documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["replaceDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["replaceCart"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setLocationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recent"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-documents/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voidDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-documents/{id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voidCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["bind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registers/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["createManual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receivables/{id}/write-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["writeOff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receivables/{id}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/barcodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addBarcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["createManual_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payables/{id}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voidExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/categories/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_8"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_9"];
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["switchOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pinLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{membershipId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptByCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete: operations["archive_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_5"];
        trace?: never;
    };
    "/stock-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{id}/drawer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["drawer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/returns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receivables/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payables/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["registerStaff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["memberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DocumentRequest: {
            /** @enum {string} */
            type: "OPENING" | "STOCK_IN" | "STOCK_OUT" | "ADJUSTMENT" | "TRANSFER";
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            counterpartyLocationId?: string;
            /** Format: uuid */
            supplierId?: string;
            /** Format: date-time */
            occurredAt?: string;
            note?: string;
            lines: components["schemas"]["LineRequest"][];
            post?: boolean;
        };
        LineRequest: {
            /** Format: uuid */
            productId: string;
            quantity: number;
            unitCost?: number;
            /** @enum {string} */
            reason?: "DAMAGED" | "EXPIRED" | "INTERNAL_USE" | "SAMPLE" | "THEFT" | "COUNT_CORRECTION" | "VOID_REVERSAL";
        };
        DocumentView: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "OPENING" | "STOCK_IN" | "STOCK_OUT" | "ADJUSTMENT" | "TRANSFER";
            /** @enum {string} */
            status?: "DRAFT" | "POSTED" | "VOID";
            documentNumber?: string;
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            counterpartyLocationId?: string;
            /** Format: uuid */
            supplierId?: string;
            /** Format: uuid */
            payableId?: string;
            /** Format: date-time */
            occurredAt?: string;
            note?: string;
            /** Format: date-time */
            postedAt?: string;
            /** Format: date-time */
            voidedAt?: string;
            lines?: components["schemas"]["LineView"][];
        };
        LineView: {
            /** Format: int32 */
            position?: number;
            /** Format: uuid */
            productId?: string;
            quantity?: number;
            unitCost?: number;
            /** @enum {string} */
            reason?: "DAMAGED" | "EXPIRED" | "INTERNAL_USE" | "SAMPLE" | "THEFT" | "COUNT_CORRECTION" | "VOID_REVERSAL";
        };
        CartRequest: {
            /** Format: uuid */
            locationId: string;
            /** @enum {string} */
            channel: "POS" | "ONLINE" | "ORDER";
            /** Format: uuid */
            cashierShiftId?: string;
            /** @enum {string} */
            priceType?: "RETAIL" | "WHOLESALE";
            cartDiscountAmount?: number;
            lines: components["schemas"]["LineRequest"][];
            hold?: boolean;
            /** Format: uuid */
            customerId?: string;
        };
        PaymentView: {
            /** @enum {string} */
            method?: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            amount?: number;
            tenderedAmount?: number;
            changeAmount?: number;
            referenceNo?: string;
        };
        SaleView: {
            /** Format: uuid */
            id?: string;
            receiptNumber?: string;
            /** @enum {string} */
            status?: "DRAFT" | "HELD" | "COMPLETED" | "VOID" | "PARTIALLY_REFUNDED" | "REFUNDED";
            /** @enum {string} */
            channel?: "POS" | "ONLINE" | "ORDER";
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            cashierShiftId?: string;
            /** Format: uuid */
            customerId?: string;
            /** @enum {string} */
            priceType?: "RETAIL" | "WHOLESALE";
            taxInclusive?: boolean;
            subtotal?: number;
            lineDiscountTotal?: number;
            cartDiscountAmount?: number;
            taxAmount?: number;
            roundingAdjustment?: number;
            total?: number;
            paidAmount?: number;
            dueAmount?: number;
            /** Format: date-time */
            soldAt?: string;
            lines?: components["schemas"]["LineView"][];
            payments?: components["schemas"]["PaymentView"][];
        };
        LocationSettingsWrite: {
            /** Format: int32 */
            reorderPoint?: number;
            shelfLocation?: string;
        };
        LocationSettingsView: {
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            productId?: string;
            /** Format: int32 */
            reorderPoint?: number;
            shelfLocation?: string;
        };
        SupplierWrite: {
            name?: string;
            phone?: string;
            address?: string;
            /** Format: int32 */
            paymentTermsDays?: number;
        };
        SupplierView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            phone?: string;
            address?: string;
            /** Format: int32 */
            paymentTermsDays?: number;
        };
        OpenRequest: {
            /** Format: uuid */
            locationId: string;
            openingFloat: number;
        };
        ShiftView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            locationId?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED";
            /** Format: uuid */
            openedBy?: string;
            /** Format: date-time */
            openedAt?: string;
            openingFloat?: number;
            /** Format: uuid */
            closedBy?: string;
            /** Format: date-time */
            closedAt?: string;
            expectedCash?: number;
            countedCash?: number;
            variance?: number;
        };
        CloseRequest: {
            countedCash: number;
        };
        CompleteRequest: {
            idempotencyKey: string;
            payments: components["schemas"]["PaymentRequest"][];
        };
        PaymentRequest: {
            /** @enum {string} */
            method: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            amount: number;
            tenderedAmount?: number;
            referenceNo?: string;
        };
        CheckoutRequest: {
            idempotencyKey: string;
            /** Format: uuid */
            locationId: string;
            /** @enum {string} */
            channel: "POS" | "ONLINE" | "ORDER";
            /** Format: uuid */
            cashierShiftId?: string;
            /** @enum {string} */
            priceType?: "RETAIL" | "WHOLESALE";
            cartDiscountAmount?: number;
            lines: components["schemas"]["LineRequest"][];
            payments: components["schemas"]["PaymentRequest"][];
            /** Format: uuid */
            customerId?: string;
        };
        ReturnRequest: {
            /** Format: uuid */
            saleId: string;
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            cashierShiftId?: string;
            /** @enum {string} */
            refundMethod: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            referenceNo?: string;
            reason?: string;
            lines: components["schemas"]["LineRequest"][];
            idempotencyKey?: string;
        };
        ReturnView: {
            /** Format: uuid */
            id?: string;
            returnNumber?: string;
            /** Format: uuid */
            saleId?: string;
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            cashierShiftId?: string;
            /** @enum {string} */
            refundMethod?: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            refundAmount?: number;
            taxAmount?: number;
            referenceNo?: string;
            reason?: string;
            /** Format: date-time */
            returnedAt?: string;
            lines?: components["schemas"]["LineView"][];
        };
        BindRequest: {
            /** Format: uuid */
            locationId: string;
            label: string;
        };
        BoundView: {
            register?: components["schemas"]["RegisterView"];
            deviceCredential?: string;
        };
        RegisterView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            locationId?: string;
            label?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            lastSeenAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        ManualRequest: {
            /** Format: uuid */
            customerId: string;
            /** Format: uuid */
            locationId: string;
            amount: number;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date */
            dueDate?: string;
            note?: string;
        };
        ReceivableView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            customerId?: string;
            customerName?: string;
            /** Format: uuid */
            locationId?: string;
            /** @enum {string} */
            sourceType?: "SALE" | "ORDER" | "MANUAL";
            /** Format: uuid */
            sourceId?: string;
            referenceNumber?: string;
            originalAmount?: number;
            settledAmount?: number;
            writtenOffAmount?: number;
            outstandingAmount?: number;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date */
            dueDate?: string;
            overdue?: boolean;
            /** @enum {string} */
            status?: "OPEN" | "PARTIALLY_SETTLED" | "SETTLED" | "WRITTEN_OFF";
            note?: string;
            settlements?: components["schemas"]["SettlementView"][];
        };
        SettlementView: {
            /** Format: uuid */
            id?: string;
            amount?: number;
            /** @enum {string} */
            method?: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            cashierShiftId?: string;
            referenceNo?: string;
            /** Format: date-time */
            paidAt?: string;
            note?: string;
        };
        WriteOffRequest: {
            reason?: string;
        };
        SettleRequest: {
            amount: number;
            /** @enum {string} */
            method: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            cashierShiftId?: string;
            referenceNo?: string;
            /** Format: date-time */
            paidAt?: string;
            note?: string;
            idempotencyKey?: string;
        };
        OpeningStockWrite: {
            /** Format: uuid */
            locationId: string;
            quantity: number;
            unitCost?: number;
        };
        ProductWrite: {
            /** Format: uuid */
            id?: string;
            sku?: string;
            name?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            defaultSupplierId?: string;
            /** @enum {string} */
            unit?: "PIECE" | "BAG" | "BOX" | "KG" | "LITRE" | "PACK";
            sizeLabel?: string;
            productGroupKey?: string;
            retailPrice?: number;
            wholesalePrice?: number;
            taxable?: boolean;
            trackInventory?: boolean;
            /** Format: int32 */
            reorderPoint?: number;
            sellInPos?: boolean;
            sellOnline?: boolean;
            active?: boolean;
            barcodes?: string[];
            openingStock?: components["schemas"]["OpeningStockWrite"][];
        };
        ProductView: {
            /** Format: uuid */
            id?: string;
            sku?: string;
            name?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            defaultSupplierId?: string;
            /** @enum {string} */
            unit?: "PIECE" | "BAG" | "BOX" | "KG" | "LITRE" | "PACK";
            sizeLabel?: string;
            productGroupKey?: string;
            retailPrice?: number;
            wholesalePrice?: number;
            taxable?: boolean;
            trackInventory?: boolean;
            /** Format: int32 */
            reorderPoint?: number;
            sellInPos?: boolean;
            sellOnline?: boolean;
            active?: boolean;
            barcodes?: string[];
        };
        BarcodeWrite: {
            barcode: string;
        };
        PayableView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            supplierId?: string;
            supplierName?: string;
            /** Format: uuid */
            locationId?: string;
            /** @enum {string} */
            sourceType?: "STOCK_DOCUMENT" | "MANUAL";
            /** Format: uuid */
            sourceId?: string;
            referenceNumber?: string;
            originalAmount?: number;
            settledAmount?: number;
            outstandingAmount?: number;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date */
            dueDate?: string;
            overdue?: boolean;
            /** @enum {string} */
            status?: "OPEN" | "PARTIALLY_SETTLED" | "SETTLED" | "CANCELLED";
            note?: string;
            settlements?: components["schemas"]["SettlementView"][];
        };
        PayRequest: {
            amount: number;
            /** @enum {string} */
            method: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "CREDIT" | "OTHER";
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            cashierShiftId?: string;
            referenceNo?: string;
            /** Format: date-time */
            paidAt?: string;
            note?: string;
            idempotencyKey?: string;
        };
        InviteRequest: {
            displayName: string;
            /** @enum {string} */
            role: "OWNER" | "STOCK_MANAGER" | "CASHIER" | "PACKER";
            /** Format: uuid */
            locationId?: string;
            phone?: string;
            pin?: string;
        };
        InviteResponse: {
            membership?: components["schemas"]["MembershipView"];
            inviteCode?: string;
        };
        MembershipView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            accountId?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "OWNER" | "STOCK_MANAGER" | "CASHIER" | "PACKER";
            /** Format: uuid */
            locationId?: string;
            /** @enum {string} */
            status?: "INVITED" | "ACTIVE" | "SUSPENDED" | "REMOVED";
            invitedPhone?: string;
            /** Format: date-time */
            inviteExpiresAt?: string;
            /** Format: date-time */
            acceptedAt?: string;
        };
        LocationCreate: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "STORE" | "WAREHOUSE";
            address?: string;
            phone?: string;
        };
        LocationView: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            /** @enum {string} */
            type?: "STORE" | "WAREHOUSE";
            address?: string;
            phone?: string;
            active?: boolean;
        };
        Mismatch: {
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            productId?: string;
            storedQuantity?: number;
            expectedQuantity?: number;
            storedAverageCost?: number;
            expectedAverageCost?: number;
            /** Format: int32 */
            balanceAfterErrors?: number;
            /** Format: int32 */
            sequenceErrors?: number;
        };
        Report: {
            /** Format: int32 */
            balancesChecked?: number;
            /** Format: int32 */
            movementsReplayed?: number;
            mismatches?: components["schemas"]["Mismatch"][];
            /** Format: int32 */
            repaired?: number;
        };
        ExpenseWrite: {
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            cashierShiftId?: string;
            amount: number;
            /** @enum {string} */
            method: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "OTHER";
            /** Format: date-time */
            paidAt?: string;
            description?: string;
            referenceNo?: string;
        };
        ExpenseView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            cashierShiftId?: string;
            amount?: number;
            /** @enum {string} */
            method?: "CASH" | "KBZ_PAY" | "WAVE_PAY" | "AYA_PAY" | "CB_PAY" | "BANK_TRANSFER" | "OTHER";
            /** Format: date-time */
            paidAt?: string;
            description?: string;
            referenceNo?: string;
            /** Format: date-time */
            voidedAt?: string;
        };
        CategoryWrite: {
            name: string;
        };
        CategoryView: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        CustomerWrite: {
            name?: string;
            phone?: string;
            /** @enum {string} */
            type?: "MEMBER" | "B2B";
            /** @enum {string} */
            defaultPriceType?: "RETAIL" | "WHOLESALE";
            creditLimit?: number;
            /** Format: int32 */
            creditTermDays?: number;
            address?: string;
            note?: string;
        };
        CustomerView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            phone?: string;
            /** @enum {string} */
            type?: "MEMBER" | "B2B";
            /** @enum {string} */
            defaultPriceType?: "RETAIL" | "WHOLESALE";
            creditLimit?: number;
            /** Format: int32 */
            creditTermDays?: number;
            outstanding?: number;
            availableCredit?: number;
            /** Format: int32 */
            loyaltyPoints?: number;
            address?: string;
            note?: string;
            archived?: boolean;
        };
        CategoryCreate: {
            name: string;
            /** Format: uuid */
            parentId?: string;
        };
        SwitchRequest: {
            /** Format: uuid */
            organizationId: string;
            deviceLabel?: string;
        };
        IssuedTokens: {
            kind?: string;
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            refreshToken?: string;
            /** Format: date-time */
            refreshTokenExpiresAt?: string;
        };
        SignupRequest: {
            phone: string;
            password: string;
            fullName: string;
            businessName: string;
            deviceLabel?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        PinLoginRequest: {
            /** Format: uuid */
            membershipId: string;
            pin: string;
        };
        LoginRequest: {
            phone: string;
            password: string;
            deviceLabel?: string;
        };
        LoginResult: {
            tokens?: components["schemas"]["IssuedTokens"];
            memberships?: components["schemas"]["PickerEntry"][];
        };
        PickerEntry: {
            /** Format: uuid */
            membershipId?: string;
            /** Format: uuid */
            organizationId?: string;
            organizationName?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "OWNER" | "STOCK_MANAGER" | "CASHIER" | "PACKER";
            /** @enum {string} */
            status?: "INVITED" | "ACTIVE" | "SUSPENDED" | "REMOVED";
        };
        AcceptCodeRequest: {
            code: string;
        };
        OrganizationUpdate: {
            name?: string;
            /** @enum {string} */
            businessType?: "RETAIL" | "WHOLESALE" | "ONLINE" | "DISTRIBUTOR" | "MULTI_BRANCH" | "FNB" | "SERVICE" | "RENTAL" | "OTHER";
            currencyCode?: string;
            taxInclusivePricing?: boolean;
            defaultTaxRate?: number;
            roundTotalToNearest?: number;
            allowNegativeStock?: boolean;
            timezone?: string;
        };
        OrganizationView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            businessType?: "RETAIL" | "WHOLESALE" | "ONLINE" | "DISTRIBUTOR" | "MULTI_BRANCH" | "FNB" | "SERVICE" | "RENTAL" | "OTHER";
            currencyCode?: string;
            taxInclusivePricing?: boolean;
            defaultTaxRate?: number;
            roundTotalToNearest?: number;
            allowNegativeStock?: boolean;
            /** @enum {string} */
            costingMethod?: "WEIGHTED_AVERAGE";
            timezone?: string;
        };
        StatusChange: {
            /** @enum {string} */
            status: "INVITED" | "ACTIVE" | "SUSPENDED" | "REMOVED";
        };
        LocationUpdate: {
            name?: string;
            address?: string;
            phone?: string;
            active?: boolean;
        };
        CategoryUpdate: {
            name?: string;
        };
        MovementView: {
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            seq?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            movedAt?: string;
            /** @enum {string} */
            type?: "OPENING" | "STOCK_IN" | "STOCK_OUT" | "SALE" | "SALE_RETURN" | "TRANSFER_IN" | "TRANSFER_OUT" | "ADJUSTMENT";
            quantity?: number;
            unitCost?: number;
            balanceAfter?: number;
            /** @enum {string} */
            referenceType?: "SALE" | "RETURN" | "STOCK_DOCUMENT";
            /** Format: uuid */
            referenceId?: string;
            referenceNumber?: string;
            /** @enum {string} */
            reason?: "DAMAGED" | "EXPIRED" | "INTERNAL_USE" | "SAMPLE" | "THEFT" | "COUNT_CORRECTION" | "VOID_REVERSAL";
            /** Format: uuid */
            createdBy?: string;
        };
        DocumentSummary: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "OPENING" | "STOCK_IN" | "STOCK_OUT" | "ADJUSTMENT" | "TRANSFER";
            /** @enum {string} */
            status?: "DRAFT" | "POSTED" | "VOID";
            documentNumber?: string;
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            counterpartyLocationId?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        BalanceView: {
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            productId?: string;
            quantity?: number;
            averageCost?: number;
            /** Format: date-time */
            lastMovementAt?: string;
        };
        Drawer: {
            openingFloat?: number;
            cashSales?: number;
            cashRepayments?: number;
            cashRefunds?: number;
            cashExpenses?: number;
            cashSupplierPayments?: number;
            expectedCash?: number;
        };
        StaffEntry: {
            /** Format: uuid */
            membershipId?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "OWNER" | "STOCK_MANAGER" | "CASHIER" | "PACKER";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    replaceDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    replaceCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    setLocationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationSettingsWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationSettingsView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierView"];
                };
            };
        };
    };
    recent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentSummary"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    voidDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShiftView"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShiftView"];
                };
            };
        };
    };
    saveCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    voidCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    hold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SaleView"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReturnView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterView"][];
                };
            };
        };
    };
    bind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoundView"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterView"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                customerId?: string;
                status?: string;
                overdue?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceivableView"][];
                };
            };
        };
    };
    createManual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceivableView"];
                };
            };
        };
    };
    writeOff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WriteOffRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceivableView"];
                };
            };
        };
    };
    settle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceivableView"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductView"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductView"];
                };
            };
        };
    };
    addBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductView"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                supplierId?: string;
                status?: string;
                overdue?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayableView"][];
                };
            };
        };
    };
    createManual_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayableView"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayableView"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembershipView"][];
                };
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InviteResponse"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationView"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationView"];
                };
            };
        };
    };
    rebuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Report"];
                };
            };
        };
    };
    list_7: {
        parameters: {
            query?: {
                locationId?: string;
                from?: string;
                to?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpenseView"][];
                };
            };
        };
    };
    record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpenseView"];
                };
            };
        };
    };
    voidExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpenseView"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    list_8: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    list_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"][];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    switchOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedTokens"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedTokens"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedTokens"];
                };
            };
        };
    };
    pinLogin: {
        parameters: {
            query?: never;
            header?: {
                "X-Register-Device"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedTokens"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResult"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PickerEntry"];
                };
            };
        };
    };
    acceptByCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PickerEntry"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierView"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductView"];
                };
            };
        };
    };
    archive_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductView"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationView"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationView"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembershipView"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationView"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    ledger: {
        parameters: {
            query: {
                locationId: string;
                productId: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovementView"][];
                };
            };
        };
    };
    balances: {
        parameters: {
            query?: {
                locationId?: string;
                productId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BalanceView"][];
                };
            };
        };
    };
    drawer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Drawer"];
                };
            };
        };
    };
    current: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShiftView"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReturnView"];
                };
            };
        };
    };
    get_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceivableView"];
                };
            };
        };
    };
    get_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayableView"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Report"];
                };
            };
        };
    };
    get_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpenseView"];
                };
            };
        };
    };
    registerStaff: {
        parameters: {
            query?: never;
            header?: {
                "X-Register-Device"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffEntry"][];
                };
            };
        };
    };
    memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PickerEntry"][];
                };
            };
        };
    };
    jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
